### PR TITLE
[WIP] APIv4 conversion

### PR DESCRIPTION
**Pull request by displague**
This is a work in progress.

Closes https://github.com/dradtke/packer-builder-linode/issues/2

### CODE REVIEW

**Comment by dradtke** [comment]
Thanks for opening this! It's quite a meaty PR, but it looks pretty good at first glance. I plan on taking a more in-depth look at it soon.

**Comment by displague** [comment]
It doesn't work yet.  I just wanted to push it somewhere for more eyes.

I was advised that the Google provider is the example to follow for best practice:
- https://github.com/hashicorp/packer/tree/master/builder/googlecompute

**Comment by dradtke** [comment]
That's good to know, I've usually consulted the Digital Ocean provider when looking for existing patterns.

**Comment by dradtke** [comment]
I merged this PR into a new [apiv4 branch](https://github.com/dradtke/packer-builder-linode/tree/apiv4), so further work can more easily be done there. Further PR's for the v4 transition should be opened up against that branch, and then once it's more stable, that branch can then be merged into master.

**Pull request closed without merging**
